# Generated by Django 5.2.3 on 2025-07-26 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercisetemplate",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="set",
            old_name="workout_exercise_id",
            new_name="workout_exercise",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="workoutexercise",
            old_name="template_id",
            new_name="template",
        ),
        migrations.RenameField(
            model_name="workoutexercise",
            old_name="workout_id",
            new_name="workout",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="ended_at",
        ),
        migrations.AddField(
            model_name="workout",
            name="duration",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="set",
            name="duration",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
