# Generated by Django 5.2.3 on 2025-08-03 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_user_id_exercisetemplate_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="duration",
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
