# Generated by Django 5.2.3 on 2025-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="height",
            field=models.IntegerField(blank=True, default=175, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="weight",
            field=models.IntegerField(blank=True, default=70, null=True),
        ),
    ]
