# Generated by Django 5.2.3 on 2025-07-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_appuser_height_appuser_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="user_vk_id",
            new_name="vk_user_id",
        ),
    ]
