# Generated by Django 5.2.3 on 2025-08-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_vk_id_appuser_vk_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
